import type { BaguaNameKey, BaguaNameRecord } from "@/lib/database/schema";

export const houtianNumberToBagua: Record<number, BaguaNameKey> = {
  1: "坎",
  2: "坤",
  3: "震",
  4: "巽",
  5: "中",
  6: "乾",
  7: "兑",
  8: "艮",
  9: "离"
};

export const baguaNameRecords: Record<BaguaNameKey, BaguaNameRecord> = {
  坎: {
    gua: "坎",
    image: "坎为水",
    element: "水",
    yinYang: "阳",
    xiantianNumber: 6,
    houtianNumber: 1,
    direction: "北方",
    season: "冬",
    coreNature: "流动、智慧、隐伏、险中求稳",
    personalityKeywords: ["聪明", "善谋", "多思", "外柔内刚", "适应力", "观察力"],
    formKeywords: ["流动", "变化", "寒冷", "不规则", "忍耐", "暧昧"],
    placeKeywords: ["江河湖海", "泉井沟渠", "湿地", "地下空间", "流动场所"],
    peopleKeywords: ["中男", "流动职业", "水产经营者", "医生", "驾驶员"],
    objectKeywords: ["水具", "液体", "墨水", "绳带", "冷藏设备", "轮子"],
    colorKeywords: ["黑色", "深色", "冷色"],
    positiveTags: ["智慧", "弹性", "洞察", "流通", "应变"],
    cautionTags: ["犹豫", "漂泊", "情绪内耗", "暧昧不清", "风险意识过重"],
    careerImage: "适合靠信息、流动、人脉与洞察打开机会；若过重，事业容易反复想太多。",
    relationshipImage: "感情里重感受和安全感，容易把话藏在心里，需要看沟通是否顺畅。",
    wealthImage: "财气有流动性，适合活水型收入；若名字收束不足，容易进出都快。",
    lifeStageTone: "坎象落在姓名位置，常提示这一阶段需要在变化中找稳定。",
    safePublicTone: "坎水不是坏象，重点是看名字有没有让智慧变成流通，而不是变成内耗。",
    internalNotes: "源自金钥匙姓名学坎卦取象；疾病、灾难等词仅作内部禁用敏感标签，不直接输出。"
  },
  坤: {
    gua: "坤",
    image: "坤为地",
    element: "土",
    yinYang: "阴",
    xiantianNumber: 8,
    houtianNumber: 2,
    direction: "西南方",
    coreNature: "承载、包容、平稳、柔顺",
    personalityKeywords: ["温厚", "守信", "踏实", "保守", "包容", "行动较慢"],
    formKeywords: ["方形", "柔软", "开阔", "稳健", "沉默", "含蓄"],
    placeKeywords: ["田园", "平地", "乡村", "仓库", "民房", "农贸市场"],
    peopleKeywords: ["母亲", "妻子", "副手", "职员", "地产相关", "群众"],
    objectKeywords: ["衣服", "瓷器", "五谷", "布帛", "食品", "日用品"],
    colorKeywords: ["黄色", "土色", "柔和色"],
    positiveTags: ["稳定", "承接", "耐力", "资源累积", "照顾力"],
    cautionTags: ["保守", "迟缓", "委屈承受", "界限不清", "过度迁就"],
    careerImage: "适合长期累积、资源整合、服务与管理支持；若过重，事业突破会慢。",
    relationshipImage: "关系里愿意包容和承担，但要留意只照顾别人而忽略自己。",
    wealthImage: "偏向土地、库存、长期稳定型财库；需要避免资金被责任慢慢占住。",
    lifeStageTone: "坤象落在姓名位置，常提示这一阶段重承接、责任和稳定基础。",
    safePublicTone: "坤土的优势是能承载，提醒是别把所有压力都变成自己的责任。",
    internalNotes: "源自金钥匙姓名学坤卦取象；疾病类资料不进入前端断语。"
  },
  震: {
    gua: "震",
    image: "震为雷",
    element: "木",
    yinYang: "阳",
    xiantianNumber: 4,
    houtianNumber: 3,
    direction: "东方",
    season: "春",
    coreNature: "启动、奋起、显现、行动",
    personalityKeywords: ["积极", "果断", "直爽", "性急", "竞争", "自尊心"],
    formKeywords: ["转动", "激烈", "高速", "移动", "上大下小", "勇敢"],
    placeKeywords: ["竹林", "闹市", "运动场", "机场", "广播电台", "繁华街道"],
    peopleKeywords: ["长男", "长子", "名人", "医生", "律师", "运动员", "执法人员"],
    objectKeywords: ["乐器", "电器", "电话", "飞机", "汽车", "音响", "麦克风"],
    colorKeywords: ["青色", "绿色", "明亮色"],
    positiveTags: ["行动", "开局", "勇气", "成长", "声量"],
    cautionTags: ["冲动", "争执", "急躁", "有声无实", "压力爆发"],
    careerImage: "事业上有启动和冲刺力，适合开创、表达、营销、执行；需避免急进。",
    relationshipImage: "关系里表达直接，容易快速推进，也需要留意语气和节奏。",
    wealthImage: "财气来自行动和机会捕捉，但不宜只冲不守。",
    lifeStageTone: "震象落在姓名位置，常提示这一阶段会被推动、被催促或需要主动突破。",
    safePublicTone: "震木能带来启动，但要让行动有方向，别让急切耗掉贵人缘。",
    internalNotes: "源自金钥匙姓名学震卦取象；碰撞与病症类词不作前端输出。"
  },
  巽: {
    gua: "巽",
    image: "巽为风",
    element: "木",
    yinYang: "阴",
    xiantianNumber: 5,
    houtianNumber: 4,
    direction: "东南方",
    coreNature: "渗透、流通、柔和、进退",
    personalityKeywords: ["柔和", "谦虚", "优柔", "艺术气质", "忙碌", "善沟通"],
    formKeywords: ["气态", "轻灵", "条形", "波动", "外实内虚", "上实下虚"],
    placeKeywords: ["山林", "花木茂盛地", "过道", "长廊", "邮局", "技术院"],
    peopleKeywords: ["长女", "妻子", "营销员", "教师", "商人", "自由职业者"],
    objectKeywords: ["扇子", "风扇", "木制品", "文具", "票据", "绳索", "纸张"],
    colorKeywords: ["绿色", "青色", "柔亮色"],
    positiveTags: ["人脉", "渗透", "传播", "柔韧", "艺术感"],
    cautionTags: ["徘徊", "不定", "空虚感", "想很多", "忙而不聚"],
    careerImage: "适合传播、教育、营销、顾问、技术与流通型行业；需避免方向飘散。",
    relationshipImage: "关系里懂得顺势和体贴，但也容易因顾虑太多而不说清楚。",
    wealthImage: "财气靠流通、人脉和细水长流；关键是把机会收束成结果。",
    lifeStageTone: "巽象落在姓名位置，常提示这一阶段靠人际、传播和持续渗透打开。",
    safePublicTone: "巽风适合做个人品牌和人际流通，提醒是别让忙碌变成消耗。",
    internalNotes: "源自金钥匙姓名学巽卦取象；疾病词仅为内部禁用参考。"
  },
  中: {
    gua: "中",
    image: "中宫土",
    element: "土",
    yinYang: "中",
    houtianNumber: 5,
    direction: "中央",
    coreNature: "承接、转换、统摄、缓冲",
    personalityKeywords: ["中和", "承接", "协调", "转换", "稳定", "缓冲"],
    formKeywords: ["中心", "枢纽", "连接", "过渡", "聚合", "沉淀"],
    placeKeywords: ["中心位置", "交汇处", "管理中枢", "家庭核心"],
    peopleKeywords: ["协调者", "管理者", "中间人", "承接者"],
    objectKeywords: ["平台", "容器", "仓储", "中枢工具"],
    colorKeywords: ["黄色", "土色", "中性色"],
    positiveTags: ["统合", "稳定", "协调", "承接", "转化"],
    cautionTags: ["压力集中", "停滞", "责任过重", "拖延", "不易切割"],
    careerImage: "适合整合资源、管理流程和承接复杂事项；需避免所有压力都集中到自己身上。",
    relationshipImage: "关系里常扮演协调者，也要看边界是否清楚。",
    wealthImage: "财气重在沉淀和规划，适合稳扎稳打，忌长期卡在中间不流动。",
    lifeStageTone: "中宫落在姓名位置，常提示这一阶段重整合、承接和转折。",
    safePublicTone: "中宫不是单一卦象，而是提醒名字里有承接与转换的核心位置。",
    internalNotes: "由后天中五延伸为姓名学中宫土气，用于笔画数归 5 的安全解释。"
  },
  乾: {
    gua: "乾",
    image: "乾为天",
    element: "金",
    yinYang: "阳",
    xiantianNumber: 1,
    houtianNumber: 6,
    direction: "西北方",
    coreNature: "刚健、规范、权威、核心",
    personalityKeywords: ["刚健", "勇武", "重义", "自尊", "高傲", "竞争"],
    formKeywords: ["高档", "精致", "坚硬", "圆润", "白色", "金黄色"],
    placeKeywords: ["大都市", "大会堂", "广场", "高楼", "名胜古地", "高级场所"],
    peopleKeywords: ["父亲", "祖父", "一把手", "名流", "专家", "领导者"],
    objectKeywords: ["金玉珠宝", "金属制品", "钟表", "镜子", "首饰", "飞机"],
    colorKeywords: ["白色", "金黄色", "强烈色"],
    positiveTags: ["领导", "权威", "格局", "规则", "贵气"],
    cautionTags: ["强硬", "孤高", "压力上身", "不易示弱", "标准过高"],
    careerImage: "事业上重格局、权威和专业背书，适合领导、管理、品牌定位。",
    relationshipImage: "关系里有保护与主导感，但要避免太硬而难以亲近。",
    wealthImage: "偏向高价值资产、专业价值和身份型财富；需要守住规则与边界。",
    lifeStageTone: "乾象落在姓名位置，常提示这一阶段重身份、权威和承担。",
    safePublicTone: "乾金有格局和领导感，提醒是刚健之外也要保留柔软与协作。",
    internalNotes: "源自两份 PDF 的乾卦取象，合并为姓名学安全文案。"
  },
  兑: {
    gua: "兑",
    image: "兑为泽",
    element: "金",
    yinYang: "阴",
    xiantianNumber: 2,
    houtianNumber: 7,
    direction: "西方",
    season: "秋",
    coreNature: "表达、悦纳、口才、亲密",
    personalityKeywords: ["喜悦", "开朗", "温和", "重情义", "多愁善感", "口才"],
    formKeywords: ["带口", "外软内坚", "下沉", "亲密", "娱乐", "议论"],
    placeKeywords: ["沼泽", "游乐场", "咖啡屋", "会议室", "小巷", "井坑"],
    peopleKeywords: ["少女", "年轻女性", "歌手", "讲演者", "以口为业者"],
    objectKeywords: ["财宝", "乐器", "锅碗瓢盆", "刀剪", "带口之物"],
    colorKeywords: ["白色", "金色", "亮色"],
    positiveTags: ["表达", "魅力", "喜悦", "沟通", "亲和"],
    cautionTags: ["口舌", "情绪反复", "过度取悦", "外软内硬", "关系黏着"],
    careerImage: "适合表达、销售、教学、娱乐、沟通与公众关系；需留意口舌边界。",
    relationshipImage: "感情里有亲和与吸引力，但也容易因期待和话语产生摩擦。",
    wealthImage: "财气常通过口才、人脉、服务和交易而来；要避免人情消费过重。",
    lifeStageTone: "兑象落在姓名位置，常提示这一阶段重沟通、人际与情感互动。",
    safePublicTone: "兑泽带来表达和魅力，提醒是关系与口舌要保持清明。",
    internalNotes: "源自金钥匙姓名学兑卦取象；色情、病症等敏感词不直接输出。"
  },
  艮: {
    gua: "艮",
    image: "艮为山",
    element: "土",
    yinYang: "阳",
    xiantianNumber: 7,
    houtianNumber: 8,
    direction: "东北方",
    coreNature: "停止、守成、阻隔、转折",
    personalityKeywords: ["保守", "固执", "稳重", "诚实", "谨慎", "安静"],
    formKeywords: ["静止", "稳定", "阻隔", "困难", "转折", "改革"],
    placeKeywords: ["山路", "丘陵", "桥梁", "仓库", "宗庙", "矿山", "大楼"],
    peopleKeywords: ["少男", "儿童", "守卫", "仓库管理员", "房地产商", "保守者"],
    objectKeywords: ["岩石", "阶梯", "石碑", "门坎", "墙壁", "座位", "屏风"],
    colorKeywords: ["黄色", "土色", "沉稳色"],
    positiveTags: ["稳定", "守成", "边界", "耐心", "沉淀"],
    cautionTags: ["迟滞", "阻隔", "固执", "孤独感", "转折压力"],
    careerImage: "事业上适合守成、管理、资产、地产、仓储和长期稳定型领域；突破速度会慢。",
    relationshipImage: "关系里重安全和边界，但表达容易慢半拍，需要避免冷处理。",
    wealthImage: "财库重沉淀与固定资产，适合长期守财；需留意流动性不足。",
    lifeStageTone: "艮象落在姓名位置，常提示这一阶段需要停下来整理，也可能遇到转折关口。",
    safePublicTone: "艮山有稳定和守成之力，提醒是别让稳定变成停滞。",
    internalNotes: "源自金钥匙姓名学艮卦取象；疾病和监狱等重词不进入公开报告。"
  },
  离: {
    gua: "离",
    image: "离为火",
    element: "火",
    yinYang: "阴",
    xiantianNumber: 3,
    houtianNumber: 9,
    direction: "南方",
    season: "夏",
    coreNature: "光明、美丽、文明、显现",
    personalityKeywords: ["聪明", "爱美", "重礼", "名誉", "冲动", "判断"],
    formKeywords: ["光明", "变化", "迅速", "流行", "华丽", "外刚内柔"],
    placeKeywords: ["学校", "图书馆", "电视台", "美容院", "画廊", "文化部门"],
    peopleKeywords: ["明星", "文人", "艺术家", "作家", "美容师", "中层干部"],
    objectKeywords: ["图书", "字画", "文件", "证件", "照片", "电脑", "广告"],
    colorKeywords: ["红色", "紫红", "明亮色"],
    positiveTags: ["曝光", "审美", "文才", "表达", "判断"],
    cautionTags: ["急躁", "虚浮", "空心感", "过度在意评价", "情绪发热"],
    careerImage: "适合曝光、内容、教育、审美、传播与专业表达；需避免只亮不稳。",
    relationshipImage: "感情里有热度和吸引力，但也要看情绪是否容易升温过快。",
    wealthImage: "财气来自被看见、作品、品牌和表达；关键是把热度转成长期价值。",
    lifeStageTone: "离象落在姓名位置，常提示这一阶段重曝光、名誉和表达判断。",
    safePublicTone: "离火带来被看见和文采，提醒是光亮之外仍要有稳定承接。",
    internalNotes: "源自金钥匙姓名学离卦取象；原文中个别基础表述按通行八卦修正为离火。"
  }
};
